<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getPersonList()
	{
		return $this->
		createQueryBuilder('p')
		->select('p')
		->orderBy('p.username')
		->getQuery()
		->getResult();
	}
}
