AppBundle\Entity\Profile:
 type: entity
 table: profile
 repositoryClass: AppBundle\Repository\ProfileRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
   length: 255
   nullable: true
  pob:
   type: string
   nullable: true
  dob:
   type: date
   nullable: true
  phone:
   type: string
   length: 20
   nullable: true
  address:
   type: text
   nullable: true
  foto:
   type: string
   nullable: true
  about:
   type: text
   nullable: true
  expertise:
   type: text
   nullable: true
  email:
   type: string
   nullable: true
 oneToOne:
  user:
   targetEntity: User
   inversedBy: profile
   joinColumn:
    name: user_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ preUpload ]
  preUpdate: [ removeUploaded, preUpload ]
  postPersist: [ upload ]
  postUpdate: [ upload ]
