AppBundle\Entity\Publikasi:
 type: entity
 table: publikasi
 repositoryClass: AppBundle\Repository\PublikasiRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  title:
   type: string
   nullable: true
  year:
   type: date
   nullable: true
  url:
   type: string
   nullable: true
 manyToOne:
  user:
   targetEntity: User
   inversedBy: publikasi
   joinColumn:
    name: user_id
    referencedColumnName: id
