AppBundle\Entity\Url:
 type: entity
 table: url
 repositoryClass: AppBundle\Repository\UrlRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  title:
   type: string
   nullable: true
  url:
   type: string
   nullable: true
 manyToOne:
  user:
   targetEntity: User
   inversedBy: url
   joinColumn:
    name: user_id
    referencedColumnName: id
