AppBundle\Entity\User:
 type: entity
 repositoryClass: AppBundle\Repository\UserRepository
 table: user
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  roles:
   type: json_array
   nullable: true
  username:
   type: string
   length: 255
   unique: true
  password:
   type: string
  salt:
   type: string
  is_active:
   type: boolean
   default: true
 oneToOne:
  profile:
   targetEntity: Profile
   mappedBy: user
 oneToMany:
  education:
   targetEntity: Education
   mappedBy: user
  url:
   targetEntity: Url
   mappedBy: user
  workexperience:
   targetEntity: WorkExperience
   mappedBy: user
 #lifecycleCallbacks:
  #prePersist: [ setSaltValue ]
